export enum IDPayTrasactionStatus {
  NOT_DONE = 1,
  NO_SUCCESS = 2,
  ERROR = 3,
  BLOCKED = 4,
  REFUNDED_TO_DEPOSITOR = 5,
  SYSTEMATIC_REFUND = 6,
  PAYMENT_CANCELED = 7,
  USER_AT_PG = 8,
  WAITING_FOR_APPROVAL = 10,
  PAYMENT_ACCEPTED = 100,
  PAYMENT_PREVIOUSLY_ACCEPTED = 101,
  PAYMENT_TRANSFERED_TO_PAYEE = 200,
}
